name: Run Unit Testing

on: [push, pull_request]

permissions:
  contents: read
  issues: read
  checks: write
  pull-requests: write

jobs:
  unit-testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unittests with nose2
      run: nose2 -v
    - name: Upload test reports
      uses: actions/upload-artifact@v3
      with:
        path: reports
      if: always()
    - name: Unit Test Results
      uses: EnricoMi/publish-unit-test-result-action@v2
      if: always()
      with:
        files: |
          reports/*.xml