name: Run Unit Testing

on: [push, pull_request]

jobs:
  unit-testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unittests with nose2
      run: nose2 -v
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "reports/**/*.xml"
        output: test-summary.md
      if: always()
    - name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: test-summary.md
      if: always()
