name: Run Unit Testing

on: [push, pull_request]

jobs:
  unit-testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unittests with nose2
      run: nose2 -v
#    - name: Upload Test Reports and Logs
#      uses: actions/upload-artifact@v2
#      with:
#        name: Test-Reports-and-Logs
#        path: reports
    - name: Test Reporter
      uses: actions/upload-artifact@v3
      if: success() || failure()
      with:
        name: reports
        path: junit-report.xml
