name: Run Unit Testing

on: [push, pull_request]

jobs:
  unit-testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unittests with nose2
      run: nose2 -v
#    - name: Upload test reports
#      uses: actions/upload-artifact@v3
#      with:
#        path: reports
#      if: always()
    - name: Publish Test Results
      uses: dorny/test-reporter@v1
      if: always()  # Ensure this step runs even if the previous steps fail
      with:
        name: Unit Test Results
        path: 'reports/junit-report.xml'
        reporter: 'github-check' # Use github-check, github-pr-review, or github-pr-check

    - name: Upload Test Report
      uses: actions/upload-artifact@v2
      with:
        name: Test-Reports
        path: |
          *.xml
          *.html