name: Run Unit Testing

on: [push, pull_request]

jobs:
  unit-testing:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Run unittests with nose2
      run: nose2 -v
    - name: Upload Test Reports and Logs
      uses: actions/upload-artifact@v2
      with:
        name: Test-Reports-and-Logs
        path: reports
    - name: Test Summary
      uses: test-summary/action@v2
      with:
        paths: "reports/*.xml"
      if: always()
    - name: DEBUG CI
      run: pwd $$ ls -la && cd reports $$ pwd && ls -la
    - name: Upload test summary
      uses: actions/upload-artifact@v3
      with:
        name: test-summary
        path: test-summary.md
      if: always()
    - name: Display links to Artifacts
      run: |
        echo "You can download the Test Reports and Logs from: ${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}#artifacts"