name: Run Unit Testing

on: [push]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests with nose2 and generate coverage report
        run: |
          nose2 -v --with-coverage
          coverage xml -o coverage.xml  # Generate XML coverage report

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        id: test-results
        if: always()
        with:
          files: "reports/*.xml"
      - name: Install xmlstarlet
        run: sudo apt-get install xmlstarlet
      - name: Extract coverage percentage
        id: extract_coverage
        run: |
          COVERAGE=$(xmlstarlet sel -t -v "sum(//coverage/class/@line-rate)" coverage.xml)
          echo "::set-output name=coverage::$COVERAGE"

      - name: Set badge color based on coverage
        shell: bash
        run: |
          COVERAGE_PERCENTAGE=$(printf "%.2f" "${{ steps.extract_coverage.outputs.coverage }}")
          if (( $(echo "$COVERAGE_PERCENTAGE < 80" | bc -l) )); then
            echo "COVERAGE_BADGE_COLOR=red" >> $GITHUB_ENV
          else
            echo "COVERAGE_BADGE_COLOR=brightgreen" >> $GITHUB_ENV
          fi

      - name: Create Test Results badge
        uses: emibcn/badge-action@808173dd03e2f30c980d03ee49e181626088eee8
        with:
          label: Tests
          status: '${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.tests }} tests, ${{ fromJSON( steps.test-results.outputs.json ).formatted.stats.runs }} runs: ${{ fromJSON( steps.test-results.outputs.json ).conclusion }}'
          color: ${{ env.BADGE_COLOR }}
          path: tests-badge.svg

      - name: Create Coverage badge
        uses: emibcn/badge-action@808173dd03e2f30c980d03ee49e181626088eee8
        with:
          label: Coverage
          status: '${{ steps.extract_coverage.outputs.coverage }}%'
          color: ${{ env.COVERAGE_BADGE_COLOR }}
          path: coverage-badge.svg

      - name: Upload badges to Gist
        # Upload only for main branch here
        if: >
          github.event_name == 'workflow_run' && github.event.workflow_run.head_branch == 'main' ||
          github.event_name != 'workflow_run' && github.ref == 'refs/heads/main'
        uses: andymckay/append-gist-action@6e8d64427fe47cbacf4ab6b890411f1d67c07f3e
        with:
          token: ${{ secrets.GIST_TOKEN }}
          gistURL: https://gist.github.com/safo-bora/fb853667de7af0650ed9fe409f24ccf9
          files: |
            tests-badge.svg
            coverage-badge.svg

