name: Run Unit Testing

on: [push, pull_request]

jobs:
  unit-testing:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        python-version: [3.11, 3.12]

    steps:
      - uses: actions/checkout@v3

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run unittests with nose2 and generate coverage report
        run: |
          nose2 -v --with-coverage
          coverage xml -o coverage.xml  # Generate XML coverage report
          pwd
          ls -la

      - name: Upload XML coverage report
        uses: actions/upload-artifact@v3
        with:
          name: xml-coverage-report
          path: coverage.xml
        if: always()

      - name: Upload test reports
        uses: actions/upload-artifact@v3
        with:
          name: test-reports
          path: reports/
        if: always()

      - name: Code Coverage Summary Report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: coverage.xml

  generate-badge:
    runs-on: ubuntu-latest
    needs: unit-testing
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install xmlstarlet
        run: sudo apt-get install xmlstarlet

      - name: Download coverage.xml artifact
        uses: actions/download-artifact@v2
        with:
          name: xml-coverage-report

      - name: Extract coverage percentage
        id: extract_coverage
        run: |
          COVERAGE=$(xmlstarlet sel -t -v "sum(//coverage/class/@line-rate)" coverage.xml)
          echo "::set-output name=coverage::$COVERAGE"

      - name: Generate badge
        id: generate_badge
        run: |
          COVERAGE=${{ steps.extract_coverage.outputs.coverage }}
          curl -s "https://img.shields.io/badge/Coverage-${COVERAGE}%25-green.svg" > coverage.svg

      - name: Upload badge
        uses: actions/upload-artifact@v2
        with:
          name: coverage-badge
          path: coverage.svg
